print("This is my project in Python, watch me closely for more updates")
print("New line of code added")
print("This line will be added to staging area using git add . ")
print("This line will be unstaged")
print("Thi is to try stash and do conflict")
