print("This is my project in Python, watch me closely for more updates")
print("New line of code added")
print("This line will be added to staging area using git add . ")
print("This line will be unstaged")
print("Na toto chci zkusit stash")
print("This is farewell message for our clients")